### ISSUE TITLE
cann't connect to facebook

### ISSUE THREAD

**Issue by wxg4dev** [sleduc/weechat-xmpp#5]
with command
/jabber add facebook xxxxx xxxxxxxxxx chat.facebook.com:5222

**Comment by sleduc** [comment]
Sorry I did not see this message until you closed it :/
In fact I did not modify the behaviour of the connection to jabber accounts, I just added the MUC support.
So I guess your problem should better be reported upstream (if not done already) : https://savannah.nongnu.org/bugs/?group=weechat
I do not use facebook myself so it would not be easy to investigate on it.

**Comment by wxg4dev** [comment]
np.  
jabber.py can't support facebook's xmpp  now.
